@startchen adv-db-class-lab

entity person {
    person_id : int <<key>>
    first_name : string
    last_name : string
    email : string
    phone_number : string
    discriminator : string
}

entity  patient {
    person_id : int <<key>>
    healthcare_number : string
}

entity parent_guardian <<weak>> {
    patient_id : int <<key>>
    person_id : int <<key>>
}

entity  doctor {
    person_id : int <<key>>
    minc_number : string
    prac_id : string
}

entity appointment {
    appointment_id : int <<key>>
    patient_id : int
    doctor_id : int
    date_time : timestampz
    notes : string
    status : string
}

entity visit {
    visit_id : int <<key>>
    appointment_id : int
    diagnosis : string
    treatment : string
    notes : string
}

entity medical_history {
    medical_history_id : int <<key>>
    patient_id : int
    heart_rate : numeric
    weight : numeric
    blood_pressure : string
    status : string
}

entity bill <<weak>> {
    bill_id : int <<key>>
    visit_id : int
    patient_id : int
    doctor_id : int
    total_amount : numeric
    amount_paid : numeric
    amount_remaining : numeric <<derived>>
    bill_date : timestampz
}

entity bill_lines <<weak>> {
    bill_line_id : int <<key>>
    bill_id : int
    description : string
    amount : numeric
}

entity payment <<weak>> {
    payment_id : int <<key>>
    bill_id : int
    amount : numeric
    method : string
    notes : string
    payment_date : timestampz
}

entity med_history_updates {
    visit_id : int <<key>>
    medical_history_id : int <<key>>
    date_time : timestampz
    notes : string
}


relationship books {
}
relationship attends {
}
relationship generates {
}
relationship pays{
}
relationship has {
}
relationship bills{
}
relationship complete {
}
relationship becomes {
}
relationship parent_guardian_of {
}
relationship child_of {
}

person -- complete
complete ->- o {patient, doctor}

appointment -(1,1)- becomes
becomes -(0,1)- visit

appointment -(0,M)- books
books -(0,1)- patient

appointment -(0,M)- attends
attends -(1,1)- doctor

medical_history -(1,1)- has
has -(1,1)- patient

visit -(1,1)- generates
generates -(1,1)- bill

visit -(1,M)- med_history_updates
med_history_updates -(1,1)- medical_history

bill -(0,M)- pays
pays -(0,1)- patient

bill -(1,M)- bill_lines

bill -(0,M)- payment

patient -(0,M)- child_of
child_of -- parent_guardian
parent_guardian -- parent_guardian_of
parent_guardian_of -(0,M)- person

doctor -(1,1)- bills
bills -(0,M)- bill

@endchen
